"""empty message

Revision ID: 4b1820faf205
Revises: e56cc6cd6f1a
Create Date: 2024-09-04 08:57:26.118881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1820faf205'
down_revision = 'e56cc6cd6f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes_categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('quizz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['quizz_id'], ['quizzes.id'], )
    )
    op.create_table('questions_quizzes',
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions_quizzes')
    op.drop_table('quizzes_categories')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
