"""empty message

Revision ID: 70df173b71f8
Revises: 9d8345922818
Create Date: 2024-08-30 16:21:37.649443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70df173b71f8'
down_revision = '9d8345922818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_answer', sa.Integer(), nullable=True))
        batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'answers', ['right_answer'], ['id'])
        batch_op.drop_column('right_answer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_answer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_1', 'answers', ['right_answer_id'], ['id'])
        batch_op.drop_column('right_answer')

    # ### end Alembic commands ###
