"""empty message

Revision ID: 714d223c424b
Revises: a4016bf2d158
Create Date: 2024-08-31 12:14:33.693859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714d223c424b'
down_revision = 'a4016bf2d158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['parent_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_category_id')

    # ### end Alembic commands ###
