"""empty message

Revision ID: 9d8345922818
Revises: 6fe74af4865b
Create Date: 2024-08-30 16:13:22.894553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8345922818'
down_revision = '6fe74af4865b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_answer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'answers', ['right_answer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('right_answer_id')

    # ### end Alembic commands ###
