"""empty message

Revision ID: e56cc6cd6f1a
Revises: f91d9c490171
Create Date: 2024-09-03 14:32:29.992466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56cc6cd6f1a'
down_revision = 'f91d9c490171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'answers', ['right_answer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_1', 'answers', ['right_answer_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
